// Left-hand control panel (pdd.md section 14.1).
//
// Two concerns live here, deliberately separated so the second is unit-testable
// without a DOM:
//
//  1. `ControlPanel` - a thin DOM view. It builds the sliders/selects/buttons,
//     reads their values, and hands them to a `ControlSink`. It owns no policy.
//  2. Pure helpers (`scenarioOverridesFromState`, `controlMessagesForSpeed`,
//     `clampSpeed`, defaults) - plain functions over plain data that encode every
//     decision the panel makes. Tests drive these directly.
//
// The panel never talks to the backend itself: setup-time fields (swarm size,
// spawn geometry, behavior, weather, turret count, decision cadence) are applied
// by re-creating the scenario + run on Start/Reset, while live-tunable fields
// (sim speed, active solver) and transport actions (pause/step/resume/stop) are
// emitted as `ControlMessage`s over the open telemetry socket. The owning app
// wires both via the `ControlSink` it passes in; we keep that boundary narrow so
// the same panel works against a real `TelemetryClient` or a test double.
//
// Types come from src/types.ts - the single wire contract. We never redefine a
// schema here.

import {
  type BehaviorProfile,
  type ControlMessage,
} from "../types";

// --------------------------------------------------------------------------- //
// Panel state - the editable scenario knobs the operator sees                  //
// --------------------------------------------------------------------------- //

/**
 * Everything the control panel can set. Mirrors the scenario / swarm_spec wire
 * shape (pdd.md 13) projected onto flat UI fields. `weather` is a profile key
 * (clear/haze/rain/fog/dust); `activeSolver` is a registered solver name.
 */
export interface ControlState {
  /** swarm_spec.count */
  swarmSize: number;
  /** swarm_spec.spawn_radius (metres) */
  spawnRadius: number;
  /** swarm_spec.spawn_arc_deg - inclusive [start, end] bearing window. */
  spawnArcStartDeg: number;
  spawnArcEndDeg: number;
  /** swarm_spec.behavior */
  behavior: BehaviorProfile;
  /** scenario.weather - a weather_profiles key. */
  weather: string;
  /** Number of turrets in the battery (geometry generated by the backend). */
  turretCount: number;
  /** scenario.decision_period (seconds) - solver cadence. */
  decisionPeriod: number;
  /** Telemetry playback / sim-time multiplier (set_speed). */
  simSpeed: number;
  /** Active solver name (set_solver). */
  activeSolver: string;
}

/** Conservative defaults aligned with the swarm_24 preset (pdd.md 18 / scaffold). */
export const DEFAULT_CONTROL_STATE: ControlState = {
  swarmSize: 24,
  spawnRadius: 4000,
  spawnArcStartDeg: 0,
  spawnArcEndDeg: 360,
  behavior: "flocking",
  weather: "clear",
  turretCount: 4,
  decisionPeriod: 0.5,
  simSpeed: 1,
  activeSolver: "auction",
};

export const BEHAVIOR_PROFILES: readonly BehaviorProfile[] = [
  "direct",
  "flocking",
  "staggered",
] as const;

/** Discrete sim-speed multipliers offered in the UI (set_speed). */
export const SPEED_STEPS: readonly number[] = [0.25, 0.5, 1, 2, 4, 8] as const;

// --------------------------------------------------------------------------- //
// Pure helpers (no DOM) - the panel's policy, unit-tested directly             //
// --------------------------------------------------------------------------- //

/** Clamp a value into [lo, hi]; NaN collapses to lo. */
export function clampNumber(v: number, lo: number, hi: number): number {
  if (Number.isNaN(v)) return lo;
  return Math.min(hi, Math.max(lo, v));
}

/** Snap an arbitrary speed to the nearest offered SPEED_STEPS multiplier. */
export function clampSpeed(multiplier: number): number {
  if (!Number.isFinite(multiplier) || multiplier <= 0) return 1;
  let best = SPEED_STEPS[0];
  let bestErr = Math.abs(Math.log(multiplier) - Math.log(best));
  for (const step of SPEED_STEPS) {
    const err = Math.abs(Math.log(multiplier) - Math.log(step));
    if (err < bestErr) {
      best = step;
      bestErr = err;
    }
  }
  return best;
}

/**
 * Project the panel state onto a scenario-override object suitable for the body
 * of POST /api/scenario (`scenario` field). Only setup-time knobs are emitted;
 * sim speed and active solver are run-time controls and intentionally excluded.
 *
 * Turret battery geometry is left to the backend: we pass the desired count and
 * let it lay out / clip the configured battery, keeping the panel ignorant of
 * physics/cost constants (those live in config, never here).
 */
export function scenarioOverridesFromState(
  state: ControlState,
): Record<string, unknown> {
  return {
    weather: state.weather,
    decision_period: state.decisionPeriod,
    turret_count: state.turretCount,
    swarm_spec: {
      count: state.swarmSize,
      behavior: state.behavior,
      spawn_radius: state.spawnRadius,
      spawn_arc_deg: [state.spawnArcStartDeg, state.spawnArcEndDeg],
    },
  };
}

/**
 * The control messages that apply a state's *live* knobs to a running socket,
 * in deterministic order: solver selection then speed. Returned as data so the
 * caller (and tests) can inspect them before they hit the wire.
 */
export function liveControlMessages(state: ControlState): ControlMessage[] {
  return [
    { action: "set_solver", solver: state.activeSolver },
    { action: "set_speed", multiplier: clampSpeed(state.simSpeed) },
  ];
}

// --------------------------------------------------------------------------- //
// Sink - the narrow boundary between the panel view and the rest of the app    //
// --------------------------------------------------------------------------- //

/**
 * What the owning app must provide. The panel calls these; it does not know
 * whether they hit REST, a WebSocket, or a test double.
 */
export interface ControlSink {
  /** (Re)build the scenario + run from setup-time knobs and begin streaming. */
  start(overrides: Record<string, unknown>): void | Promise<void>;
  /** Tear down the current run and rebuild from current knobs (Reset). */
  reset(overrides: Record<string, unknown>): void | Promise<void>;
  /** Emit a live control message over the open socket (pause/resume/step/stop,
   *  set_solver, set_speed). */
  send(msg: ControlMessage): void;
  /** Open the scenario editor drawer (optional - wired by app). */
  openEditor?(): void;
  /** Start swarm evolution (optional - wired by app). */
  startEvolve?(): void;
}

// --------------------------------------------------------------------------- //
// DOM view                                                                     //
// --------------------------------------------------------------------------- //

export interface ControlPanelOptions {
  /** Element the panel mounts into. */
  root: HTMLElement;
  /** Where panel actions go. */
  sink: ControlSink;
  /** Initial field values. Defaults to DEFAULT_CONTROL_STATE. */
  initial?: Partial<ControlState>;
  /** Solver names to offer (from GET /api/solvers). Falls back to a single entry
   *  derived from the initial active solver. */
  solverNames?: readonly string[];
  /** Weather profile keys to offer (from GET /api/weather). */
  weatherNames?: readonly string[];
  /** Injectable document for non-browser hosts / tests. */
  document?: Document;
}

const WEATHER_FALLBACK = ["clear", "haze", "rain", "fog", "dust"] as const;

/**
 * The left control panel. Renders inputs for every pdd.md 14.1 knob and the
 * Start / Pause / Step / Reset (+ Resume / Stop) transport, reads them on demand,
 * and routes changes through the injected `ControlSink`.
 */
export class ControlPanel {
  readonly state: ControlState;
  private readonly doc: Document;
  private readonly root: HTMLElement;
  private readonly sink: ControlSink;
  private readonly solverNames: readonly string[];
  private readonly weatherNames: readonly string[];

  // Cached input refs (populated by mount()).
  private inputs: Partial<Record<keyof ControlState, HTMLInputElement | HTMLSelectElement>> = {};
  private running = false;
  private paused = false;

  constructor(opts: ControlPanelOptions) {
    this.root = opts.root;
    this.sink = opts.sink;
    this.doc = opts.document ?? this.root.ownerDocument ?? globalThis.document;
    this.state = { ...DEFAULT_CONTROL_STATE, ...(opts.initial ?? {}) };
    this.solverNames =
      opts.solverNames && opts.solverNames.length > 0
        ? opts.solverNames
        : [this.state.activeSolver];
    this.weatherNames =
      opts.weatherNames && opts.weatherNames.length > 0
        ? opts.weatherNames
        : WEATHER_FALLBACK;
    this.mount();
  }

  // --- public API --------------------------------------------------------- //

  /** Current panel values (read live from the DOM inputs). */
  getState(): ControlState {
    this.syncFromInputs();
    return { ...this.state };
  }

  /** Reflect external run status (e.g. an `ack`/`end` from the socket). */
  setRunning(running: boolean): void {
    this.running = running;
    if (!running) this.paused = false;
    this.refreshButtons();
  }

  setPaused(paused: boolean): void {
    this.paused = paused;
    this.refreshButtons();
  }

  setSolver(name: string): void {
    const sel = this.inputs.activeSolver as HTMLSelectElement | undefined;
    if (sel) sel.value = name;
    this.state.activeSolver = name;
  }

  // --- DOM construction --------------------------------------------------- //

  private el<K extends keyof HTMLElementTagNameMap>(
    tag: K,
    attrs: Record<string, string> = {},
    text?: string,
  ): HTMLElementTagNameMap[K] {
    const node = this.doc.createElement(tag);
    for (const [k, v] of Object.entries(attrs)) node.setAttribute(k, v);
    if (text !== undefined) node.textContent = text;
    return node;
  }

  private field(
    key: keyof ControlState,
    label: string,
    input: HTMLInputElement | HTMLSelectElement,
  ): HTMLElement {
    const wrap = this.el("div", { class: "beam-field" });
    const lab = this.el("label", { class: "beam-field-label" }, label);
    wrap.appendChild(lab);
    wrap.appendChild(input);
    this.inputs[key] = input;
    return wrap;
  }

  private numberInput(
    value: number,
    attrs: Record<string, string>,
  ): HTMLInputElement {
    const inp = this.el("input", { type: "number", ...attrs });
    inp.value = String(value);
    inp.addEventListener("change", () => this.syncFromInputs());
    return inp;
  }

  private select(
    value: string,
    options: readonly string[],
  ): HTMLSelectElement {
    const sel = this.el("select");
    for (const opt of options) {
      const o = this.el("option", { value: opt }, opt);
      if (opt === value) o.setAttribute("selected", "selected");
      sel.appendChild(o);
    }
    sel.value = value;
    sel.addEventListener("change", () => this.syncFromInputs());
    return sel;
  }

  private button(label: string, onClick: () => void): HTMLButtonElement {
    const b = this.el("button", { type: "button" }, label);
    b.addEventListener("click", onClick);
    return b;
  }

  private mount(): void {
    this.root.classList.add("beam-controls");
    this.root.replaceChildren();

    const s = this.state;

    // --- setup-time knobs ---
    this.root.appendChild(
      this.field(
        "swarmSize",
        "Swarm size",
        this.numberInput(s.swarmSize, { min: "1", max: "512", step: "1" }),
      ),
    );
    this.root.appendChild(
      this.field(
        "spawnRadius",
        "Spawn radius (m)",
        this.numberInput(s.spawnRadius, { min: "100", max: "20000", step: "100" }),
      ),
    );
    this.root.appendChild(
      this.field(
        "spawnArcStartDeg",
        "Spawn arc start (deg)",
        this.numberInput(s.spawnArcStartDeg, { min: "0", max: "360", step: "5" }),
      ),
    );
    this.root.appendChild(
      this.field(
        "spawnArcEndDeg",
        "Spawn arc end (deg)",
        this.numberInput(s.spawnArcEndDeg, { min: "0", max: "360", step: "5" }),
      ),
    );
    this.root.appendChild(
      this.field("behavior", "Behavior", this.select(s.behavior, BEHAVIOR_PROFILES)),
    );
    this.root.appendChild(
      this.field("weather", "Weather", this.select(s.weather, this.weatherNames)),
    );
    this.root.appendChild(
      this.field(
        "turretCount",
        "Turrets",
        this.numberInput(s.turretCount, { min: "1", max: "32", step: "1" }),
      ),
    );
    this.root.appendChild(
      this.field(
        "decisionPeriod",
        "Decision period (s)",
        this.numberInput(s.decisionPeriod, { min: "0.05", max: "5", step: "0.05" }),
      ),
    );

    // --- live knobs ---
    this.root.appendChild(
      this.field("activeSolver", "Active solver", this.select(s.activeSolver, this.solverNames)),
    );

    const speedSel = this.select(
      String(s.simSpeed),
      SPEED_STEPS.map((x) => String(x)),
    );
    // sim speed is live: apply immediately on change.
    speedSel.addEventListener("change", () => {
      this.syncFromInputs();
      if (this.running) this.sink.send({ action: "set_speed", multiplier: clampSpeed(this.state.simSpeed) });
    });
    this.inputs.simSpeed = speedSel;
    {
      const wrap = this.el("div", { class: "beam-field" });
      wrap.appendChild(this.el("label", { class: "beam-field-label" }, "Sim speed"));
      wrap.appendChild(speedSel);
      this.root.appendChild(wrap);
    }

    // active solver is live: apply immediately on change.
    (this.inputs.activeSolver as HTMLSelectElement | undefined)?.addEventListener("change", () => {
      this.syncFromInputs();
      if (this.running) this.sink.send({ action: "set_solver", solver: this.state.activeSolver });
    });

    // --- transport ---
    const bar = this.el("div", { class: "beam-controls-buttons" });
    this.btnStart = this.button("Start", () => this.onStart());
    this.btnPause = this.button("Pause", () => this.onPauseResume());
    this.btnStep = this.button("Step", () => this.onStep());
    this.btnReset = this.button("Reset", () => this.onReset());
    bar.appendChild(this.btnStart);
    bar.appendChild(this.btnPause);
    bar.appendChild(this.btnStep);
    bar.appendChild(this.btnReset);
    this.root.appendChild(bar);

    const editBtn = this.button("Edit Scenario", () => this.sink.openEditor?.());
    editBtn.className = "beam-edit-scenario";
    this.root.appendChild(editBtn);

    const evolveBtn = this.button("Evolve Swarm", () => this.sink.startEvolve?.());
    evolveBtn.className = "beam-evolve-btn";
    this.root.appendChild(evolveBtn);

    this.refreshButtons();
  }

  private btnStart!: HTMLButtonElement;
  private btnPause!: HTMLButtonElement;
  private btnStep!: HTMLButtonElement;
  private btnReset!: HTMLButtonElement;

  // --- value sync --------------------------------------------------------- //

  private syncFromInputs(): void {
    const num = (key: keyof ControlState, lo: number, hi: number): number => {
      const inp = this.inputs[key] as HTMLInputElement | undefined;
      if (!inp) return this.state[key] as number;
      return clampNumber(Number(inp.value), lo, hi);
    };
    const str = (key: keyof ControlState): string => {
      const inp = this.inputs[key] as HTMLSelectElement | undefined;
      return inp ? inp.value : (this.state[key] as string);
    };

    this.state.swarmSize = Math.round(num("swarmSize", 1, 512));
    this.state.spawnRadius = num("spawnRadius", 100, 20000);
    this.state.spawnArcStartDeg = num("spawnArcStartDeg", 0, 360);
    this.state.spawnArcEndDeg = num("spawnArcEndDeg", 0, 360);
    this.state.behavior = str("behavior") as BehaviorProfile;
    this.state.weather = str("weather");
    this.state.turretCount = Math.round(num("turretCount", 1, 32));
    this.state.decisionPeriod = num("decisionPeriod", 0.05, 5);
    this.state.activeSolver = str("activeSolver");
    const speedInp = this.inputs.simSpeed as HTMLSelectElement | undefined;
    if (speedInp) this.state.simSpeed = clampSpeed(Number(speedInp.value));
  }

  // --- transport handlers ------------------------------------------------- //

  private onStart(): void {
    this.syncFromInputs();
    this.running = true;
    this.paused = false;
    this.refreshButtons();
    void this.sink.start(scenarioOverridesFromState(this.state));
  }

  private onPauseResume(): void {
    if (!this.running) return;
    if (this.paused) {
      this.paused = false;
      this.sink.send({ action: "resume" });
    } else {
      this.paused = true;
      this.sink.send({ action: "pause" });
    }
    this.refreshButtons();
  }

  private onStep(): void {
    if (!this.running) return;
    // Stepping implies (and leaves) a paused stream.
    this.paused = true;
    this.sink.send({ action: "step", epochs: 1 });
    this.refreshButtons();
  }

  private onReset(): void {
    this.syncFromInputs();
    if (this.running) this.sink.send({ action: "stop" });
    this.running = false;
    this.paused = false;
    this.refreshButtons();
    void this.sink.reset(scenarioOverridesFromState(this.state));
  }

  private refreshButtons(): void {
    if (!this.btnPause) return;
    this.btnPause.textContent = this.paused ? "Resume" : "Pause";
    this.btnPause.disabled = !this.running;
    this.btnStep.disabled = !this.running;
    this.btnStart.disabled = this.running;
  }
}
